### ISSUE TITLE
RFC: Retry with implicit reconnect

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/db-extractor-retry-proxy#1]
There are many issues caused by the connection being dropped or timed out. If the retry proxy got the db connection it could internally check for connection aliveness and reconnect automatically. It would only need some common interface specifying the check/reconnect method. 

Ref.: https://keboola.slack.com/archives/C035LGNK5/p1563270370012900?thread_ts=1563095204.001400&cid=C035LGNK5

**Comment by pivnicek** [comment]
we should switch to https://github.com/keboola/retry which has a callable interface where you can give it something to run on error.  That would solve this issue.

**Comment by tomasfejfar** [comment]
This repository is actually not used (and keboola/retry is) and should probably be archived. (@ondrajodas ?)
